Improving logging for Ctv1
aws-cloudformation/cloudformation-cli pull request #996
Opened 2023-05-03 20:40 UTC by rajdnp

*Issue #, if available:*

*Description of changes:*
Improving logging for Ctv1 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Testing : 
Unit testing 
Pre-commit hooks are successful 

Screenshots : 
<img width="1920" alt="Error1" src="https://user-images.githubusercontent.com/118321621/236044572-c6add290-d02d-489f-ac90-87e220ab49a2.png">
<img width="1148" alt="Error2" src="https://user-images.githubusercontent.com/118321621/236044574-33c6ad26-b148-48b6-8e6f-8d13189d3edc.png">
<img width="1147" alt="Error3" src="https://user-images.githubusercontent.com/118321621/236044575-3cb9fc03-36b0-4a2b-b30a-8e7ee2cf3e1c.png">
<img width="1143" alt="error4" src="https://user-images.githubusercontent.com/118321621/236044577-b1cebdef-db91-49ed-b5e9-68fd9f461c37.png">
![Error5](https://user-images.githubusercontent.com/118321621/236044580-bdd9103d-d3bf-44a0-b35f-e7218f0c0872.png)

2023-05-03 20:49 UTC, joshuadeanhall requested changes
The changes look good but are there no unit tests that we can add to validate the expected behavior?

2023-05-05 17:43 UTC, joshuadeanhall approved these changes

2023-05-05 17:45 UTC, rajdnp commented
> The changes look good but are there no unit tests that we can add to validate the expected behavior?

Added more test https://github.com/aws-cloudformation/cloudformation-cli/pull/996/files#diff-56099aed7f1376770c545e5382edc0717d3a93376cb6371f3184f534c2f64b9e

2023-05-10 20:30 UTC, kddejong approved these changes

2023-05-11 17:55 UTC, merged